apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: khaos-daemon
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: khaos-daemon
  template:
    metadata:
      labels:
        name: khaos-daemon
    spec:
      hostPID: true
      containers:
        - name: khaos-agent
          image: khaos-image:latest
          imagePullPolicy: Never
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - SYS_RESOURCE
                - NET_ADMIN
                - BPF
          volumeMounts:
            - name: headers
              mountPath: /kernel-headers
              readOnly: true
            - name: bpf
              mountPath: /sys/fs/bpf
            - name: modules
              mountPath: /lib/modules
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
      volumes:
        - name: headers
          hostPath:
            path: /usr/src
            type: Directory
        - name: bpf
          hostPath:
            path: /sys/fs/bpf
        - name: modules
          hostPath:
            path: /lib/modules
        - name: sys
          hostPath:
            path: /sys
      nodeSelector:
        kubernetes.io/os: linux

